# . See reference.yml for explanation for explanation of all options.
#
#  auth:
#    token:
#      realm: "https://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"

server:
  addr: ":5001"
  certificate: "/certs/auth.crt"
  key: "/certs/auth.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

# LDAP authentication.
# Authentication is performed by first binding to the server, looking up the user entry
# by using the specified filter, and then re-binding using the matched DN and the password provided.
ldap_auth:
  addr: "ldap-sn-slave1.computecanada.ca:389"
  tls: "starttls"
  # In case bind DN and password is required for querying user information,
  # specify them here. Plain text password is read from the file.
  # bind_dn: "uid=serviceaccount,ou=it,dc=example,dc=com"
  # Make sure you remove newlines and carriage returns from the password file.
  # bind_password_file: /tmp/ldap_password.txt.clean
  # User query settings. ${account} is expanded from auth request 
  base: "dc=computecanada,dc=ca"
  filter: "(uid=${account})"

  
acl:
    
  # This will allow authenticated users to pull/push
  - match:
      account: /.+/
      name: "${account}/*"
    actions: ['*']
  
  # The user "serviceaccount" (from LDAP) may not perform any docker actions
  # like push or pull.
  - match: {account: "serviceaccount"}
    actions: []
